on:
  push:
    tags:
      - "v*"

name: Create Github Release

jobs:
  build:
    name: Create Github Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          prerelease: true
          body: |
            Please refer to [CHANGELOG.md](https://github.com/datatorch/vuehookse/blob/master/CHANGELOG.md)
